### ISSUE TITLE
`DateTimeRange::Closed` is contradictory on whether `end` is open or closed

### ISSUE THREAD

**Issue by yongqli** [databento/databento-rs#13]
The docs say:

    The end date time (inclusive).

But it also says:

    A closed interval with an inclusive start time and an exclusive end time.

**Comment by threecgreen** [comment]
Thanks for reporting this issue. `end` is always exclusive

**Comment by threecgreen** [comment]
Fixed in ff28566a373032b527ef72bf79f273ea954c4b92
